# Site settings
title:       Pixyll
email:       your_email@example.com
author:      John Otander
description: "A simple, beautiful theme for Jekyll that emphasizes content rather than aesthetic fluff."
baseurl:     ""
url:         "http://pixyll.com"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     3
sass:
  compressed: true
